name: app

description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - assets/images/grips/back_three_L.png
    - assets/images/grips/back_three_R.png
    - assets/images/grips/back_two_L.png
    - assets/images/grips/back_two_R.png
    - assets/images/grips/front_three_L.png
    - assets/images/grips/front_three_R.png
    - assets/images/grips/front_two_L.png
    - assets/images/grips/front_two_R.png
    - assets/images/grips/middle_two_L.png
    - assets/images/grips/middle_two_R.png
    - assets/images/grips/mono_index_L.png
    - assets/images/grips/mono_index_R.png
    - assets/images/grips/mono_middle_L.png
    - assets/images/grips/mono_middle_R.png
    - assets/images/grips/mono_ring_L.png
    - assets/images/grips/mono_ring_R.png
    - assets/images/grips/mono_pinky_L.png
    - assets/images/grips/mono_pinky_R.png
    - assets/images/grips/open_hand_L.png
    - assets/images/grips/open_hand_R.png
    - assets/images/grips/half_crimp_L.png
    - assets/images/grips/half_crimp_R.png
    - assets/images/grips/full_crimp_L.png
    - assets/images/grips/full_crimp_R.png

  uses-material-design: false
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/typography/Staatliches-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/typography/Lato-Regular.ttf
        - asset: assets/typography/Lato-Bold.ttf
          weight: 700