name: app

description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.14.0
  auto_size_text: ^2.1.0
  built_collection: ^4.3.2
  built_value: ^7.0.8
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
  uuid: ^2.0.4
  rxdart: ^0.23.1
  wakelock: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  built_value_generator: ^7.0.8

flutter:

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/boards/
    - assets/images/custom_board/
    - assets/images/grips/
    - assets/images/icons/

  uses-material-design: false
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/typography/Staatliches-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/typography/Lato-Regular.ttf
        - asset: assets/typography/Lato-Bold.ttf
          weight: 700